ax = [ 0 5.4 0 1.99];
set(ax, 'Box'         , 'on'     , ...
    'TickDir'     , 'in'     , ...
    'FontSize'    , 10       , ...
    'FontName'    , 'times'   , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'LineWidth'   , 1         );
grid off
figureHandle = gcf;
%# make all text in the figure to size 14 and bold
set(findall(figureHandle,'type','text'),'fontname','times','fontSize',16)